'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Artikel
    Public Property artnr As Integer
    Public Property lfnr As Integer
    Public Property pnr As Integer
    Public Property vorrat As Nullable(Of Integer)
    Public Property preis As Nullable(Of Decimal)

    Public Overridable Property Lieferanten As Lieferanten
    Public Overridable Property Produkte As Produkte

End Class
