'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AufgabenTab
    Public Property ID As Integer
    Public Property Aufgabenbeschreibung As String

    Public Overridable Property RaumschiffeTab As ICollection(Of RaumschiffeTab) = New HashSet(Of RaumschiffeTab)

End Class
