'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BildTab
    Public Property HimmelskoerperID As Integer
    Public Property Bilddaten As Byte()
    Public Property Himmelskoerper_ID As Integer

    Public Overridable Property HimmelskoerperTab As HimmelskoerperTab

End Class
