'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HimmelskoerperTab
    Public Property ID As Integer
    Public Property Name As String
    Public Property Masse_in_kg As Double
    Public Property HimmelskoerperTyp_ID As Integer

    Public Overridable Property HimmelskoerperTypenTab As HimmelskoerperTypenTab
    Public Overridable Property RaumschiffeTab As ICollection(Of RaumschiffeTab) = New HashSet(Of RaumschiffeTab)
    Public Overridable Property Sterne_Planeten_MondeTab As ICollection(Of Sterne_Planeten_MondeTab) = New HashSet(Of Sterne_Planeten_MondeTab)
    Public Overridable Property UrlSammlungenTab As ICollection(Of UrlSammlungenTab) = New HashSet(Of UrlSammlungenTab)
    Public Overridable Property UmlaufbahnenTab As ICollection(Of UmlaufbahnenTab) = New HashSet(Of UmlaufbahnenTab)
    Public Overridable Property UmlaufbahnenTab1 As ICollection(Of UmlaufbahnenTab) = New HashSet(Of UmlaufbahnenTab)

End Class
