'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RaumschiffeTab
    Public Property Start_der_Mission As Date
    Public Property ID As Integer
    Public Property Himmelskoerper_ID As Integer
    Public Property Land_ID As Integer
    Public Property RaumschiffAufgaben_ID As Integer

    Public Overridable Property HimmelskoerperTab As HimmelskoerperTab
    Public Overridable Property LaenderTab As LaenderTab
    Public Overridable Property RaumschiffAufgabenTab As RaumschiffAufgabenTab

End Class
