'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SpektralklasseTab
    Public Property ID As Integer
    Public Property Name As String
    Public Property Farbe As String
    Public Property Tmin As Double
    Public Property Tmax As Double
    Public Property Masse_Hauptreihenstern_in_Sonnenmassen As Double

    Public Overridable Property HimmelskoerperTab As ICollection(Of HimmelskoerperTab) = New HashSet(Of HimmelskoerperTab)

End Class
