'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sterne_Planeten_MondeTab
    Public Property Aequatordurchmesser_in_km As Double
    Public Property Polardurchmesser_in_km As Double
    Public Property Oberflaechentemperatur_in_K As Double
    Public Property Rotationsperiode_in_Stunden As Double
    Public Property Fallbeschleunigung_in_meter_pro_sec As Double
    Public Property Rotationsachsenneigung_in_Grad As Double
    Public Property HimmelskoerperID As Integer
    Public Property Leuchtkraft_in_Lsonne As Double

    Public Overridable Property HimmelskoerperTab As HimmelskoerperTab

End Class
