'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UmlaufbahnenTab
    Public Property Laenge_grosse_Halbachse_in_km As Double
    Public Property Exzentritzitaet As Double
    Public Property Umlaufdauer_in_Tagen As Double
    Public Property Mittlere_Umlaufgeschwindigkeit_in_km_pro_sec As Double
    Public Property TrabantID As Integer
    Public Property Zentralobjekt_ID As Integer

    Public Overridable Property HimmelskoerperTab As HimmelskoerperTab
    Public Overridable Property HimmelskoerperTab1 As HimmelskoerperTab

End Class
