'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UrlSammlungenTab
    Public Property ID As Integer
    Public Property Kurzbeschreibung As String
    Public Property Url As String
    Public Property UrlTyp As Integer
    Public Property Himmelskoerper_ID As Integer

    Public Overridable Property HimmelskoerperTab As HimmelskoerperTab

End Class
